language: r
cache: packages

env:
  global:
    - secure: "g1gf+fzPIfxkQsaVy4Ugj8XOW2aNCGJI2N5s1VXd0HOkdGoKRvjm0CdqE6pGyHUKuIkc6UxpYkM2R96vE3C/2ISVbsOCDKV9Mvq3K1BWOXni2fS0GkV35aPDm0Wzu1uHkxTXuC//qNHl7h+dgC7a1i23z91q5eFEMmqIqkOw4uLwHBU5w5jdbwwjKkgg0BUvkPnPD4QufrGwxQkT3lW+CPyi2E5O1RviTxiZFfVp0OcZTbZwYF5BKLX1V2fPm0EvGQh2yZzd9EJNOiT5pqQLK010BVMIasCuRyosiLfWRZuJ3RIYX3Meqd4RxvvogzmHQCa0CxMNWtYSj8A9qqwhrRN8QWaJD8bIHJQcsba6ua0Z1a9cWOgzJQ/BS7a6BrUy2NZCeYiGWl+91jz07b2lgiZ7I3A4l5GXrx7OTyAIwEkHYUMjmLmEea+Pi5RsaDinHwhN3Ym4uwHWWiFOUTxEsJpmBFyPLOuWW6CYvGPjEfObIrovUOtRRT5jfAD1b13hWoJlPtDGAhl2VpjGr1x25MWCHWzpDRi1hYJcGlAbFbKydOb6d4k1jmvQYGL+JU6gf7w9oNyQSiDbC8yJUzHzdKY1uBeVb0XrrpJwaZcZtplL/d3WL8ibxSpQwuFRXbgLkmvLoy3Oirj2H7NJY/xr0AWylx0+REuhWmhcgb7y1Bs="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
